/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UnitConverter;

import com.sun.xml.internal.ws.api.addressing.AddressingVersion;
import java.awt.event.KeyEvent;
import javax.swing.JComboBox;

/**
 *
 * @author admin
 */
public class UnitConverter extends javax.swing.JFrame {

    /**
     * Creates new form UnitConverter
     */
    //Boolean
    boolean distanceMode, temperatureMode, pressureMode;
    
    //Combobox strings
    String[] categories = {"Distance","Temperature","Pressure"};
    String[] distanceUnits = {"Meter (m)","Centimeter (cm)","Milimeter (mm)","Kilometer (km)", "Feet (ft)", "Inch (in)"};
    String[] temperatureUnits = {"Celsius (°C)","Fahrenheit (°F)","Kelvin (K)"};
    String[] pressureUnits = {"atmosphere (atm)", "bar (b)", "hectoPascal (hPa)", "Pascal (Pa)", "milimeter of Hg (mmHg)"};
    
    float mft=3.28084f, ftm=0.3048f; //meters to feet and feet to meters
    float mti=39.3701f, itm=0.0254f; //meters to inches and inches to meters
    float atmb=1.01325f; //atmosphere to bar
    float atmhecto=1013.25f; //atmosphere to hectopascal
    float atmmmhg=760;//atmosphere to mmHg
    float barmmhg=750.061683f;//bar to mmHg
    float Paatm=101.325f;

   
    public UnitConverter() {
        initComponents();
        //jComboBoxCategory.setLightWeightPopupEnabled(false);
        
        //Category Combobox
        for (int i=0;i<categories.length;i++) {
            jComboBoxCategory.addItem(categories[i]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBoxFrom = new javax.swing.JComboBox<>();
        jComboBoxTo = new javax.swing.JComboBox<>();
        jComboBoxCategory = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UnitConverter");

        jButton1.setText("Convert");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxFrom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxFrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxFromKeyPressed(evt);
            }
        });

        jComboBoxTo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxToActionPerformed(evt);
            }
        });
        jComboBoxTo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBoxToKeyPressed(evt);
            }
        });

        jComboBoxCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoryActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("From");

        jTextFieldFrom.setText("1");
        jTextFieldFrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFromKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("To");

        jTextFieldTo.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Choose");

        jMenu1.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(111, 111, 111))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel4)))
                        .addContainerGap(320, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jComboBoxCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoryActionPerformed
        // TODO add your handling code here:
        //System.out.println("hey");
        switch (jComboBoxCategory.getSelectedItem().toString())
        {
            case "Distance":
                System.out.println("Distance mode");
                reinitBool();
                distanceMode=true;
                printBool();
                fillComboBox(jComboBoxFrom, distanceUnits);
                fillComboBox(jComboBoxTo, distanceUnits);
                break;
            case "Temperature":
                System.out.println("Temperature mode");
                reinitBool();
                temperatureMode=true;
                printBool();
                fillComboBox(jComboBoxFrom, temperatureUnits);
                fillComboBox(jComboBoxTo, temperatureUnits);
                break;
            case "Pressure":
                System.out.println("Pressure mode");
                reinitBool();
                pressureMode=true;
                printBool();
                fillComboBox(jComboBoxFrom, pressureUnits);
                fillComboBox(jComboBoxTo, pressureUnits);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jComboBoxCategoryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        convert();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldFromKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFromKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            convert();
    }//GEN-LAST:event_jTextFieldFromKeyPressed

    private void jComboBoxToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxToActionPerformed
        // TODO add your handling code here:
        //convert();
    }//GEN-LAST:event_jComboBoxToActionPerformed

    private void jComboBoxToKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxToKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            convert();
    }//GEN-LAST:event_jComboBoxToKeyPressed

    private void jComboBoxFromKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxFromKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER)
            convert();
    }//GEN-LAST:event_jComboBoxFromKeyPressed

    private void printBool(){
        System.out.println(distanceMode);
        System.out.println(temperatureMode);
        System.out.println(pressureMode);
    }
    
    private void reinitBool(){
        distanceMode=false;
        temperatureMode=false;
        pressureMode=false;
    }
    
    private void fillComboBox(JComboBox box,String[] units){
        box.removeAllItems();
        for (int i=0;i<units.length;i++)
            box.addItem(units[i]);
        System.out.println("Filled!");
    }
    
    private void convert(){
        float from=0, result=0;
        from=Float.parseFloat(jTextFieldFrom.getText());
        
        if (distanceMode){
            switch (jComboBoxFrom.getSelectedItem().toString()) {
                case "Meter (m)"://from m
                    switch (jComboBoxTo.getSelectedItem().toString()) {
                        case "Milimeter (mm)"://to mm
                            result=from*1000;
                            break;
                        case "Centimeter (cm)"://to cm
                            result=from*100;
                            break;
                        case "Kilometer (km)"://to km
                            result=from/1000;
                            break;
                        case "Feet (ft)"://to ft
                            result=from*mft;
                            break;
                        case "Inch (in)"://to in
                            result=from*mti;
                            break;
                        default:
                            result=from;
                            break;
                    }
                    break;
                case "Milimeter (mm)"://from mm
                    switch (jComboBoxTo.getSelectedItem().toString()) {
                        case "Meter (m)"://to m
                            result=from/1000;
                            break;
                        case "Centimeter (cm)"://to cm
                            result=from/10;
                            break;
                        case "Kilometer (km)"://to km
                            result=from/1000000;
                            break;
                        case "Feet (ft)":
                            result=from*mft/1000;
                            break;
                        case "Inch (in)":
                            result=from*mti/1000;
                            break;
                        default:
                            result=from;
                            break;
                    }
                    break;
                case "Centimeter (cm)"://from cm
                    switch (jComboBoxTo.getSelectedItem().toString()) {
                        case "Meter (m)"://to m
                            result=from/100;
                            break;
                        case "Milimeter (mm)"://to mm
                            result=from*10;
                            break;
                        case "Kilometer (km)"://to km
                            result=from/100000;
                            break;
                        case "Feet (ft)":
                            result=from*mft/100;
                            break;
                        case "Inch (in)":
                            result=from*mti/100;
                            break;
                        default:
                            result=from;
                            break;
                    }
                    break;
                case "Kilometer (km)"://from km
                    switch (jComboBoxTo.getSelectedItem().toString()) {
                        case "Meter (m)":
                            result=from*1000;
                            break;
                        case "Centimeter (cm)":
                            result=from*100000;
                            break;
                        case "Milimeter (mm)":
                            result=from*1000000;
                            break;
                        case "Feet (ft)":
                            result=from*mft*1000;
                            break;
                        case "Inch (in)":
                            result=from*mti*1000;
                            break;
                        default:
                            result=from;
                            break;
                    }
                    break;
                case "Feet (ft)"://from ft
                    switch (jComboBoxTo.getSelectedItem().toString()) {
                        case "Meter (m)":
                            result=from*ftm;
                            break;
                        case "Centimeter (cm)":
                            result=from*ftm*100;
                            break;
                        case "Milimeter (mm)":
                            result=from*ftm*1000;
                            break;
                        case "Kilometer (km)":
                            result=from*ftm/1000;
                            break;
                        case "Inch (in)":
                            result=from*ftm*mti;
                            break;
                        default:
                            result=from;
                            break;
                    }
                    break;
                    case "Inch (in)"://from in
                    switch (jComboBoxTo.getSelectedItem().toString()) {
                        case "Meter (m)":
                            result=from*itm;
                            break;
                        case "Centimeter (cm)":
                            result=from*itm*100;
                            break;
                        case "Milimeter (mm)":
                            result=from*itm*1000;
                            break;
                        case "Kilometer (km)":
                            result=from*itm/1000;
                            break;
                        case "Feet (ft)":
                            result=from*itm*mft;
                            break;
                        default:
                            result=from;
                            break;
                    }
                    break;
                default:
                    break;
            }
        }
        if (temperatureMode) {
            switch (jComboBoxFrom.getSelectedItem().toString()) {
                case "Celsius (°C)":
                    switch (jComboBoxTo.getSelectedItem().toString()) {
                        case "Fahrenheit (°F)":
                            result=from*9/5+32;
                            break;
                        case "Kelvin (K)":
                            result=from+273.15f;
                            break;
                        default:
                            result=from;
                            break;
                    }
                    break;
                case "Fahrenheit (°F)":
                    switch (jComboBoxTo.getSelectedItem().toString()) {
                        case "Celsius (°C)":
                            result=(from-32)*5/9;
                            System.out.println("fah-cel");
                            break;
                        case "Kelvin (K)":
                            result=(from-32)*5/9+273.15f;
                            System.out.println("fah-kel");
                            break;
                        default:
                            result=from;
                            break;
                    }
                    break;
                case "Kelvin (K)":
                    switch (jComboBoxTo.getSelectedItem().toString()) {
                        case "Celsius (°C)":
                            result=from-273.15f;
                            break;
                        case "Fahrenheit (°F)":    
                            result=(from-273.15f)*9/5+32;
                            break;
                        default:
                            result=from;
                            break;
                    }
                default:
                    break;
            }
        }
        
        if (pressureMode){
            switch (jComboBoxFrom.getSelectedItem().toString()){
                case "atmosphere (atm)":
                    switch (jComboBoxTo.getSelectedItem().toString()){
                        case "bar (b)":
                            result=from*atmb;
                            break;
                        case "hectoPascal (hPa)":   
                            result=from*atmhecto;
                            break;
                        case "Pascal (Pa)":
                            result=from*atmhecto*100;
                            break;
                        case "milimeter of Hg (mmHg)":
                            result=from*atmmmhg;
                            break;
                        default:
                            result=from;
                            break;
                    }
                    break;
                case "bar (b)":
                    switch (jComboBoxTo.getSelectedItem().toString()){
                        case "atmosphere (atm)":
                            result=from/atmb;
                            break;
                        case "hectoPascal (hPa)":
                            result=from*1000;
                            break;
                        case "Pascal (Pa)":
                            result=from*100000;
                            break;
                        case "milimeter of Hg (mmHg)":
                            result=from*barmmhg;
                            break;
                        default:
                            result=from;
                    }
                    break;
                    case "hectoPascal (hPa)":
                        switch (jComboBoxTo.getSelectedItem().toString()){
                            case "atmosphere (atm)":
                                result=from/atmhecto;
                                break;
                            case "bar (b)":
                                result=from/1000;
                                break;
                            case "Pascal (Pa)":
                                result=from*100;
                                break;
                            case "milimeter of Hg (mmHg)":
                                result=from*barmmhg/1000;
                                break;
                            default:
                                result=from;
                                break;
                        }
                        break;
                    case "Pascal (Pa)":
                        switch (jComboBoxTo.getSelectedItem().toString()){
                            case "atmosphere (atm)":
                                result=from/Paatm;
                                break;
                            case "bar (b)":
                                result=from/100000;
                                break;
                            case "hectoPascal (hPa)":
                                result=from/100;
                                break;
                            case "milimeter of Hg (mmHg)":
                                result=from*barmmhg/100000;
                                break;
                            default:
                                result=from;
                                break;
                        }
                        break;
                    case "milimeter of Hg (mmHg)":
                        switch (jComboBoxTo.getSelectedItem().toString()){
                            case "atmosphere (atm)":
                                result=from/atmmmhg;
                                break;
                            case "bar (b)":
                                result=from/barmmhg;
                                break;
                            case "hectoPascal (hPa)":
                                result=from/barmmhg*1000;
                                break;
                            case "Pascal (Pa)":
                                result=from/barmmhg*100000;
                                break;
                            default:
                                result=from;
                                break;
                        }
                        break;
                    
            }
        }
        
        jTextFieldTo.setText(String.valueOf(result));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnitConverter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnitConverter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxCategory;
    private javax.swing.JComboBox<String> jComboBoxFrom;
    private javax.swing.JComboBox<String> jComboBoxTo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTextFieldFrom;
    private javax.swing.JTextField jTextFieldTo;
    // End of variables declaration//GEN-END:variables
}
